### ISSUE TITLE
Source code of script used to create the qcow2 images

### ISSUE THREAD

**Issue by Th0masL** [OpenNebula/marketplace#32]
Hello,

I would like to have a clear understanding on what is installed in the Linux Images that are available through the Marketplace.

Where can I find the source code of the script used to create the qcow2 images available on the Marketplace?

Thanks

Thomas

**Comment by vholer** [comment]
The building mechanism is not public.

The images are mostly the prebuilt ones from distribution with similar polishments:
- remove cloud-init (and extra unnecessary packages like snapd, fwupd, linux firmware, ...),
- install one-context (and extra useful packages like haveged, ...)
- upgrade system,
- drop pkg. caches,
- reconfigure sshd not to use password authentication,
- fix kernel parameters not to use serial console and consistent network device naming (but ethX),
- run virt-sysprep to cleanup all rest instance specific data.
